# ==============================
# FILE: railway.toml
# ==============================
[build]
root = "client"
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
# Serve the prebuilt React app
startCommand = "npx serve -s build -l $PORT"
