# ==============================
# FILE: railway.toml
# ==============================

# ---------- FRONTEND ----------
[build.frontend]
root = "client"
builder = "NIXPACKS"
buildCommand = "npm install && CI=false npm run build"

[deploy.frontend]
startCommand = "npx serve -s build -l $PORT"

# ---------- BACKEND ----------
[build.backend]
root = "server"
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy.backend]
startCommand = "node server.js"
