# FILE: railway.toml
[build]
root = "client"                 # <— key fix: build in client/
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npx serve -s build -l $PORT"
